language: node_js
node_js:
- '8'
- stable
sudo: false
before_install:
- yarn global add greenkeeper-lockfile@1
install:
- yarn install
before_script:
- greenkeeper-lockfile-update
script:
- npm run test --silent
after_script:
- greenkeeper-lockfile-upload
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
